# Generated by Django 5.2.7 on 2025-10-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useraccount_language_useraccount_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
