# Generated by Django 5.2.7 on 2025-10-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_frist_name_useraccount_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
