# Generated by Django 5.2.7 on 2025-10-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_useraccount_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='warning',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
