# Generated by Django 5.2.7 on 2025-11-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_useraccount_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='country',
            field=models.CharField(default='USA', max_length=16, verbose_name='country'),
        ),
    ]
