# Generated by Django 5.2.7 on 2025-11-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_mathlevels'),
        ('authentication', '0007_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='math_levels',
            field=models.ManyToManyField(blank=True, related_name='users', to='administration.mathlevels'),
        ),
    ]
