# Generated by Django 5.2.7 on 2025-12-02 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_useraccount_math_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
