# Generated by Django 5.2.7 on 2026-06-10 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('he', 'Hebrew')], default='en', help_text='Original language of the comment', max_length=10),
        ),
        migrations.CreateModel(
            name='CommentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='post.commentmodel')),
            ],
            options={
                'verbose_name': 'Comment Translation',
                'verbose_name_plural': 'Comment Translations',
                'unique_together': {('comment', 'language')},
            },
        ),
    ]
