# Generated by Django 5.2.7 on 2026-06-30 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_commentmodel_language_commenttranslation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostNotInterested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_interested_by', to='post.postmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_interested_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Not Interested',
                'verbose_name_plural': 'Post Not Interested',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
