# Generated by Django 5.2.7 on 2025-10-27 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_commentreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('he', 'Hebrew')], default='en', help_text='Original language of the post', max_length=10),
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='post.postmodel')),
            ],
            options={
                'verbose_name': 'Post Translation',
                'verbose_name_plural': 'Post Translations',
                'unique_together': {('post', 'language')},
            },
        ),
    ]
