# Generated by Django 5.2.7 on 2026-08-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postview_add_post_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='postview',
            name='post_postview_user_post_idx',
        ),
        migrations.AddField(
            model_name='postview',
            name='view_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='postview',
            name='viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
