# Generated by Django 5.2.7 on 2026-08-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_badge_studentprogress_dailyactivity_earnedbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='category',
            field=models.CharField(choices=[('Streak', 'Streak'), ('Engagement', 'Engagement'), ('Academic', 'Academic'), ('Social', 'Social'), ('Challenge', 'Challenge'), ('Special', 'Special')], default='Social', max_length=20),
        ),
    ]
