# Generated by Django 5.2.7 on 2025-11-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
