# Generated by Django 5.2.7 on 2025-11-14 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_slug_alter_classroom_room_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='creator',
            field=models.ForeignKey(default='7bd549b5-d53a-434f-95bd-a1dd6812719c', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
