# Generated by Django 5.2.7 on 2025-12-04 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classroom_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('challenge_name', models.CharField()),
                ('joined_count', models.PositiveIntegerField()),
                ('time_left', models.DateTimeField()),
            ],
        ),
    ]
