# Generated by Django 5.2.7 on 2025-12-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classroomchallenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomchallenge',
            name='classroom',
            field=models.ForeignKey(default='e012bea1-c11e-41c7-8427-ee4be088ad24', on_delete=django.db.models.deletion.CASCADE, related_name='challenge', to='classroom.classroom'),
            preserve_default=False,
        ),
    ]
