# Generated by Django 5.2.7 on 2025-12-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_classroomchallenge_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomchallenge',
            name='joined_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
