# Generated by Django 5.2.7 on 2025-12-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_classroomchallenge_joined_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomchallenge',
            name='joined_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
