# Generated by Django 5.2.7 on 2025-12-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_classroomchallenge_joined_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomchallenge',
            name='challenge_description',
            field=models.CharField(default='hi'),
            preserve_default=False,
        ),
    ]
