# Generated by Django 5.2.7 on 2025-12-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_classroomchallenge_created_at_challengequestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomchallenge',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
