# Generated by Django 5.2.7 on 2025-12-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_classroomchallenge_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomchallenge',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
