# Generated by Django 5.2.7 on 2025-12-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_classroomchallenge_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomchallenge',
            name='time_left',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
