# Generated by Django 5.2.7 on 2025-10-28 00:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recent_activity', models.CharField(choices=[('post_created', 'Post Created'), ('comment_added', 'Comment Added'), ('user_registered', 'User Registered'), ('login', 'User Logged In'), ('logout', 'User Logged Out'), ('profile_updated', 'Profile Updated')], help_text='Type of recent activity performed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
