# Generated by Django 5.2.7 on 2025-10-28 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overview',
            name='role',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='overview',
            name='recent_activity',
            field=models.CharField(choices=[('new_user_created', 'New User Created'), ('user_banned', 'User Banned'), ('admin_logged_in', 'Admin Logged In')], help_text='Type of recent activity performed', max_length=50),
        ),
    ]
