# Generated by Django 5.2.7 on 2025-10-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_overview_full_name_overview_role_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OverView',
            new_name='RecentActivity',
        ),
    ]
