# Generated by Django 5.2.7 on 2025-12-13 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_supportticket_supportmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classroom_point', models.PositiveIntegerField(default=0)),
                ('upvote_point', models.PositiveIntegerField(default=0)),
                ('daily_challenge_point', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
