# Generated by Django 5.2.7 on 2025-12-16 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_pointadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('grade', models.IntegerField()),
                ('number_of_questions', models.PositiveIntegerField()),
                ('points', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='challenges/')),
                ('publishing_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='challenges', to='administration.mathlevels')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('answer', models.CharField(max_length=255)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='administration.dailychallenge')),
            ],
        ),
    ]
