# Generated by Django 5.2.7 on 2026-07-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathlevels',
            name='level_type',
            field=models.CharField(choices=[('general', 'General Math Level'), ('mep', 'MEP Math Level')], default='general', max_length=20),
        ),
    ]
