# Generated by Django 5.2.7 on 2026-08-11 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_mathlevels_level_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeQuestionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_question_text', models.TextField()),
                ('translated_answer', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='administration.challengequestion')),
            ],
            options={
                'unique_together': {('question', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DailyChallengeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.CharField(max_length=255)),
                ('translated_description', models.TextField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='administration.dailychallenge')),
            ],
            options={
                'unique_together': {('challenge', 'language')},
            },
        ),
    ]
