# Generated by Django 5.2.7 on 2026-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_challengequestiontranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengequestiontranslation',
            name='translated_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailychallengetranslation',
            name='translated_name',
            field=models.TextField(),
        ),
    ]
