# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_alter_challengequestiontranslation_translated_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathLevelTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_name', models.TextField()),
                ('math_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='administration.mathlevels')),
            ],
            options={
                'unique_together': {('math_level', 'language')},
            },
        ),
    ]
