# Generated by Django 5.2.7 on 2026-08-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_mathleveltranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DummyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
