# Generated by Django 5.2.7 on 2025-12-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_classroomchallenge_created_at_challengequestion_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattend',
            name='classroom',
            field=models.ForeignKey(default='e012bea1-c11e-41c7-8427-ee4be088ad24', on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attends', to='classroom.classroom'),
            preserve_default=False,
        ),
    ]
