# Generated by Django on manually

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_reportuser_blockuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
