# Generated by Django 5.2.7 on 2026-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_conversationparticipant_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
