# Generated by Django 5.2.7 on 2026-08-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_message_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
