# Generated by Django 5.2.7 on 2026-08-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_chatsession_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='post_id',
        ),
    ]
